server:
  port: 9090

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ewm_stats}
    username: ${SPRING_DATASOURCE_USERNAME:stats}
    password: ${SPRING_DATASOURCE_PASSWORD:stats}

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC

  sql:
    init:
      mode: always
      platform: postgresql

  flyway:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics